version: '3.5'
services:
  api1: # API - Instância 01
    image: lucasmadeira/rinhabackend
    container_name: api1
    hostname: api1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pessoas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    expose:
      - "8080"
    networks:
      - rinhabackend-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1.25GB'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://api1:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


  api2: # API - Instância 02
    image: lucasmadeira/rinhabackend
    container_name: api2
    hostname: api2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pessoas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    expose:
      - "8080"
    networks:
      - rinhabackend-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1.25GB'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://api2:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx: # Load Balancer
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinhabackend-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'


  db: # Banco de dados
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pessoas
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rinhabackend-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '0.5GB'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
networks:
  rinhabackend-network:
    driver: bridge

